### ISSUE TITLE
Error Active Directory Authentication

### ISSUE THREAD

**Issue by fernandohb** [rbCAS/CASinoApp#18]
We trying to integrate Casino with active directory, below the logs "/home/casino/log/production.log"

```
Processing by CASino::SessionsController#new as HTML
  Rendered vendor/bundle/ruby/gems/casino-4.0.1/app/views/casino/application/_messages.html.erb (2.6ms)
  Rendered vendor/bundle/ruby/gems/casino-4.0.1/app/views/casino/application/_footer.html.erb (1.3ms)
  Rendered vendor/bundle/ruby/gems/casino-4.0.1/app/views/casino/sessions/new.html.erb within layouts/application (55.3ms)
Completed 200 OK in 73ms (Views: 57.7ms | ActiveRecord: 10.9ms)
Started POST "/login" for 157.86.255.134 at 2015-06-12 11:02:38 -0300
Processing by CASino::SessionsController#create as HTML
  Parameters: {"utf8"=>"â", "authenticity_token"=>"dAwOyIIWGbSA3RHVFFp8FZuVidvIzyIvV4M8m4Vc+6M=", "lt"=>"LT-14341177531709-CKMSB1lC6OerN5xq0LDCUJKI5NVXe4dP10pFz6mf", "username"=>"*********", "password"=>"[FILTERED]", "button"=>""}
Completed 500 Internal Server Error in 15ms

Errno::ECONNRESET (Connection reset by peer - SSL_connect):
  vendor/bundle/ruby/gems/net-ldap-0.11/lib/net/ldap/connection.rb:54:in `connect'
  vendor/bundle/ruby/gems/net-ldap-0.11/lib/net/ldap/connection.rb:54:in `wrap_with_ssl'
  vendor/bundle/ruby/gems/net-ldap-0.11/lib/net/ldap/connection.rb:95:in `setup_encryption'
  vendor/bundle/ruby/gems/net-ldap-0.11/lib/net/ldap/connection.rb:25:in `initialize'
  vendor/bundle/ruby/gems/net-ldap-0.11/lib/net/ldap.rb:1223:in `new'
  vendor/bundle/ruby/gems/net-ldap-0.11/lib/net/ldap.rb:1223:in `new_connection'
  vendor/bundle/ruby/gems/net-ldap-0.11/lib/net/ldap.rb:672:in `block in open'
  vendor/bundle/ruby/gems/net-ldap-0.11/lib/net/ldap/instrumentation.rb:19:in `instrument'
  vendor/bundle/ruby/gems/net-ldap-0.11/lib/net/ldap.rb:670:in `open'
  vendor/bundle/ruby/gems/net-ldap-0.11/lib/net/ldap.rb:885:in `bind_as'
  vendor/bundle/ruby/gems/casino-ldap_authenticator-3.0.0/lib/casino/ldap_authenticator.rb:42:in `authenticate'
  vendor/bundle/ruby/gems/casino-ldap_authenticator-3.0.0/lib/casino/ldap_authenticator.rb:13:in `validate'
  vendor/bundle/ruby/gems/casino-4.0.1/app/processors/casino/authentication_processor.rb:10:in `block in validate_login_credentials'
  vendor/bundle/ruby/gems/casino-4.0.1/app/processors/casino/authentication_processor.rb:8:in `each'
  vendor/bundle/ruby/gems/casino-4.0.1/app/processors/casino/authentication_processor.rb:8:in `validate_login_credentials'
  vendor/bundle/ruby/gems/casino-4.0.1/app/controllers/casino/sessions_controller.rb:23:in `create'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/abstract_controller/base.rb:189:in `process_action'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_controller/metal/rendering.rb:10:in `process_action'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `call'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `call'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `call'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:229:in `call'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:229:in `block in halting'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/abstract_controller/callbacks.rb:19:in `process_action'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/notifications.rb:159:in `block in instrument'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/notifications.rb:159:in `instrument'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/abstract_controller/base.rb:136:in `process'
  vendor/bundle/ruby/gems/actionview-4.1.8/lib/action_view/rendering.rb:30:in `process'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_controller/metal.rb:196:in `dispatch'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_controller/metal.rb:232:in `block in action'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:82:in `call'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:50:in `call'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:73:in `block in call'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:59:in `each'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:59:in `call'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:678:in `call'
  vendor/bundle/ruby/gems/railties-4.1.8/lib/rails/engine.rb:514:in `call'
  vendor/bundle/ruby/gems/railties-4.1.8/lib/rails/railtie.rb:194:in `public_send'
  vendor/bundle/ruby/gems/railties-4.1.8/lib/rails/railtie.rb:194:in `method_missing'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:73:in `block in call'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:59:in `each'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:59:in `call'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:678:in `call'
  vendor/bundle/ruby/gems/http_accept_language-2.0.5/lib/http_accept_language/middleware.rb:14:in `call'
  vendor/bundle/ruby/gems/rack-1.5.3/lib/rack/etag.rb:23:in `call'
  vendor/bundle/ruby/gems/rack-1.5.3/lib/rack/conditionalget.rb:35:in `call'
  vendor/bundle/ruby/gems/rack-1.5.3/lib/rack/head.rb:11:in `call'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_dispatch/middleware/flash.rb:254:in `call'
  vendor/bundle/ruby/gems/rack-1.5.3/lib/rack/session/abstract/id.rb:225:in `context'
  vendor/bundle/ruby/gems/rack-1.5.3/lib/rack/session/abstract/id.rb:220:in `call'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/query_cache.rb:36:in `call'
  vendor/bundle/ruby/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:82:in `run_callbacks'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/gems/railties-4.1.8/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/gems/railties-4.1.8/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/gems/railties-4.1.8/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/gems/actionpack-4.1.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/gems/rack-1.5.3/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/gems/rack-1.5.3/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/gems/activesupport-4.1.8/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  vendor/bundle/ruby/gems/rack-1.5.3/lib/rack/sendfile.rb:112:in `call'
  vendor/bundle/ruby/gems/railties-4.1.8/lib/rails/engine.rb:514:in `call'
  vendor/bundle/ruby/gems/railties-4.1.8/lib/rails/application.rb:144:in `call'
  vendor/bundle/ruby/gems/railties-4.1.8/lib/rails/railtie.rb:194:in `public_send'
  vendor/bundle/ruby/gems/railties-4.1.8/lib/rails/railtie.rb:194:in `method_missing'
  /usr/local/share/gems/gems/passenger-5.0.6/lib/phusion_passenger/rack/thread_handler_extension.rb:85:in `process_request'
  /usr/local/share/gems/gems/passenger-5.0.6/lib/phusion_passenger/request_handler/thread_handler.rb:155:in `accept_and_process_next_request'
  /usr/local/share/gems/gems/passenger-5.0.6/lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  /usr/local/share/gems/gems/passenger-5.0.6/lib/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads'
  /usr/local/share/gems/gems/passenger-5.0.6/lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
```

**Comment by pencil** [comment]
For whatever reason, the SSL handshake fails. Please check the LDAP server log for details.
